export const ingredientList = [
  {
    name: "Potato",
    origin: "Potatoes",
    price: "50",
    quantity: "1",
    experience: "90",
    time: 0.2,  
    necessaryLevel: "1",
    category: "Farming",
  },  
  {
    name: "Cotton",
    origin: "Cotton Tree",
    price: "930",
    quantity: "5-8",
    experience: "5000",
    time: 5,
    necessaryLevel: "1",
    category: "Farming",
  },
  {
    name: "Corn",
    origin: "Corn",
    price: "300",
    quantity: "2-3",
    experience: "1250",
    time: 5,
    necessaryLevel: "3",
    category: "Farming",
  },
  {
    name: "Wheat",
    origin: "Wheat",
    price: "150",
    quantity: "1-3",
    experience: "500",
    time: 2,
    necessaryLevel: "5",
    category: "Farming",
  },
  {
    name: "Apple",
    origin: "Apple Tree",
    price: "2000",
    quantity: "1-2",
    experience: "2500",
    time: 2.5,
    necessaryLevel: "7",
    category: "Farming",
  },
  {
    name: "Carrot",
    origin: "Carrots",
    price: "110",
    quantity: "1",
    experience: "200",
    time: 0.45,
    necessaryLevel: "10",
    category: "",
  },
  {
    name: "Grape",
    origin: "Grapes",
    price: "300",
    quantity: "1",
    experience: "500",
    time: 2,
    area: "1x1",
    necessaryLevel: "15",
    category: "Farming",
  },
  {
    name: "Blueberry",
    origin: "Blueberrys",
    price: "80",
    quantity: "3-5",
    experience: "500",
    time: 120,
    area: "1x1",
    necessaryLevel: "17",
    category: "Farming",
  },
  {
    name: "Cabbage",
    origin: "Cabbages",
    price: "300",
    quantity: "1",
    experience: "500",
    time: 2,
    necessaryLevel: "20",
    category: "Farming",
  },
  {
    name: "Orange",
    origin: "Orange Tree",
    price: "4000",
    quantity: "1-2",
    experience: "5000",
    time: 5,
    necessaryLevel: "22",
    category: "Farming",
  },
  {
    name: "Onion",
    origin: "Onions",
    price: "300",
    quantity: "1-2",
    experience: "750",
    time: 3,
    necessaryLevel: "25",
    category: "Farming",
  },
  {
    name: "Strawberry",
    origin: "Strawberrys",
    price: "130",
    quantity: "2-4",
    experience: "625",
    time: 2.5,
    necessaryLevel: "27",
    category: "Farming",
  },
  {
    name: "Beans",
    origin: "Beans",
    price: "190",
    quantity: "3-5",
    experience: "1250",
    time: 5,
    necessaryLevel: "30",
    category: "Farming",
  },
  {
    name: "Bananas",
    origin: "Banana Tree",
    price: "3200",
    quantity: "2-4",
    experience: "8000",
    time: 8,
    necessaryLevel: "32",
    category: "Farming",
  },
  {
    name: "Pumpkin",
    origin: "Pumpkin",
    price: "1200",
    quantity: "1",
    experience: "2000",
    time: 8,
    necessaryLevel: "35",
    category: "Farming",
  },
  {
    name: "Watermelon",
    origin: "Watermelon",
    price: "1500",
    quantity: "1",
    experience: "2500",
    time: 10,
    necessaryLevel: "37",
    category: "Farming",
  },
  {
    name: "Pea",
    origin: "Peas",
    price: "245",
    quantity: "3-5",
    experience: "1625",
    time: 6.5,
    necessaryLevel: "0",
    category: "Farming",
  },
  {
    name: "Moonberry",
    origin: "Moonberry",
    price: "530",
    quantity: "1-3",
    experience: "1750",
    time: 7,
    necessaryLevel: "42",
    category: "Farming",
  },
  {
    name: "Garlic",
    origin: "Garlic",
    price: "275",
    quantity: "2-4",
    experience: "1375",
    time: 5.5,
    necessaryLevel: "45",
    category: "Farming",
  },
  {
    name: "Acorn",
    origin: "Acorn Tree",
    price: "6400",
    quantity: "2-4",
    experience: "16000",
    time: 16,
    necessaryLevel: "47",
    category: "Farming",
  },
  {
    name: "Brocolli",
    origin: "Brocolli",
    price: "500",
    quantity: "1-2",
    experience: "1250",
    time: 5,
    necessaryLevel: "50",
    category: "Farming",
  },
  {
    name: "Sunberry",
    origin: "Sunberries",
    price: "750",
    quantity: "1-3",
    experience: "2500",
    time: 10,
    necessaryLevel: "52",
    category: "Farming",
  },
  {
    name: "Pepper",
    origin: "Peppers",
    price: "360",
    quantity: "3-5",
    experience: "2375",
    time: 9.5,
    necessaryLevel: "55",
    category: "Farming",
  },
  {
    name: "Cherry",
    origin: "Cherries   ",
    price: "2800",
    quantity: "2-4",
    experience: "7000",
    time: 7,
    necessaryLevel: "57",
    category: "Farming",
  },

 
  
];
