export const ingredientList = [
  {
    name: "Potato",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Potato",
        price: 50,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 1,
        xp: 90,
        time: 20,
      },
    ],
  },

  {
    name: "Cotton",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Cotton Tree",
        price: 930,
        minQuantity: 5,
        maxQuantity: 8,
        necessaryLevel: 1,
        xp: 5000,
        time: 300,
      },
    ],
  },
  {
    name: "Corn",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Corn",
        price: 300,
        minQuantity: 2,
        maxQuantity: 3,
        necessaryLevel: 3,
        xp: 1250,
        time: 300,
      },
    ],
  },
  {
    name: "Wheat",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Wheat",
        price: 150,
        minQuantity: 1,
        maxQuantity: 3,
        necessaryLevel: 5,
        xp: 500,
        time: 120,
      },
    ],
  },

  {
    name: "Apple",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Apple Tree",
        price: 2000,
        minQuantity: 1,
        maxQuantity: 2,
        necessaryLevel: 7,
        xp: 2500,
        time: 150,
      },
    ],
  },
  {
    name: "Carrot",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Carrots",
        price: 110,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 10,
        xp: 200,
        time: 45,
      },
    ],
  },
  {
    name: "Grape",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Grapes",
        price: 300,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 15,
        xp: 500,
        time: 120,
      },
    ],
  },
  {
    name: "Blueberry",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Blueberrys",
        price: 80,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 17,
        xp: 500,
        time: 120,
      },
    ],
  },
  {
    name: "Cabbage",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Cabbages",
        price: 300,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 20,
        xp: 500,
        time: 120,
      },
    ],
  },
  {
    name: "Orange",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Orange Tree",
        price: 4000,
        minQuantity: 1,
        maxQuantity: 2,
        necessaryLevel: 22,
        xp: 5000,
        time: 300,
      },
    ],
  },
  {
    name: "Onion",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Onions",
        price: 300,
        minQuantity: 1,
        maxQuantity: 2,
        necessaryLevel: 25,
        xp: 750,
        time: 180,
      },
    ],
  },
  {
    name: "Strawberry",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Strawberrys",
        price: 130,
        minQuantity: 2,
        maxQuantity: 4,
        necessaryLevel: 27,
        xp: 625,
        time: 150,
      },
    ],
  },
  {
    name: "Beans",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Beans",
        price: 190,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 30,
        xp: 1250,
        time: 300,
      },
    ],
  },
  {
    name: "Banana",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Banana Tree",
        price: 3200,
        minQuantity: 2,
        maxQuantity: 4,
        necessaryLevel: 32,
        xp: 8000,
        time: 480,
      },
    ],
  },
  {
    name: "Pumpkin",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Pumpkin",
        price: 1200,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 35,
        xp: 2000,
        time: 480,
      },
    ],
  },
  {
    name: "Watermelon",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Watermelon",
        price: 1500,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 37,
        xp: 2500,
        time: 600,
      },
    ],
  },
  {
    name: "Pea",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Peas",
        price: 245,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 40,
        xp: 1625,
        time: 390,
      },
    ],
  },
  {
    name: "Moonberry",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Moonberry",
        price: 530,
        minQuantity: 1,
        maxQuantity: 3,
        necessaryLevel: 42,
        xp: 1750,
        time: 420,
      },
    ],
  },
  {
    name: "Garlic",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Garlic",
        price: 275,
        minQuantity: 2,
        maxQuantity: 4,
        necessaryLevel: 45,
        xp: 1375,
        time: 330,
      },
    ],
  },
  {
    name: "Acorn",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Acorn Tree",
        price: 6400,
        minQuantity: 2,
        maxQuantity: 4,
        necessaryLevel: 47,
        xp: 1600,
        time: 960,
      },
    ],
  },
  {
    name: "Brocolli",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Brocolli",
        price: 500,
        minQuantity: 1,
        maxQuantity: 3,
        necessaryLevel: 50,
        xp: 1250,
        time: 300,
      },
    ],
  },
  {
    name: "Sunberry",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Sunberries",
        price: 750,
        minQuantity: 1,
        maxQuantity: 3,
        necessaryLevel: 52,
        xp: 2500,
        time: 600,
      },
    ],
  },
  {
    name: "Pepper",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Peppers",
        price: 360,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 55,
        xp: 2375,
        time: 570,
      },
    ],
  },
  {
    name: "Cherry",
    category: "Farming",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Cherries",
        price: 2800,
        minQuantity: 2,
        maxQuantity: 4,
        necessaryLevel: 57,
        xp: 7000,
        time: 420,
      },
    ],
  },
  //Husbandry itens
  {
    name: "Egg",
    category: "Husbandry",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Small Chicken Pen",
        price: 2000,
        minQuantity: 4,
        maxQuantity: 6,
        necessaryLevel: 1,
        xp: 2000,
        time: 140,
      },
      {
        name: "Medium Chicken Pen",
        price: 2000,
        minQuantity: 9,
        maxQuantity: 14,
        necessaryLevel: 30,
        xp: 4500,
        time: 120,
      },
    ],
  },
  {
    name: "Shank",
    category: "Husbandry",
    isGathering: false,
    isCrafting: true,
    isDroplable: false,
    source: [
      {
        name: "Pig",
        price: 700,
        minQuantity: 3,
        maxQuantity: 4,
        necessaryLevel: 1,
        xp: 8000,
        time: 480,
      },
      {
        name: "Small Goat",
        price: 2200,
        minQuantity: 4,
        maxQuantity: 7,
        necessaryLevel: 10,
        xp: 6500,
        time: 390,
      },
      {
        name: "Small Sheep",
        price: 2900,
        minQuantity: 8,
        maxQuantity: 12,
        necessaryLevel: 20,
        xp: 12000,
        time: 720,
      },
      {
        name: "Medium Pig",
        price: 700,
        minQuantity: 6,
        maxQuantity: 9,
        necessaryLevel: 40,
        xp: 18000,
        time: 480,
      },
      {
        name: "Medium Goat",
        price: 2200,
        minQuantity: 9,
        maxQuantity: 14,
        necessaryLevel: 50,
        xp: 14600,
        time: 390,
      },
      {
        name: "Medium Sheep",
        price: 2900,
        minQuantity: 18,
        maxQuantity: 27,
        necessaryLevel: 60,
        xp: 27000,
        time: 720,
      },
    ],
  },
  {
    name: "Milk",
    category: "Husbandry",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Small Goat",
        price: 2200,
        minQuantity: 2,
        maxQuantity: 3,
        necessaryLevel: 10,
        xp: 2500,
        time: 150,
      },
      {
        name: "Small Cow",
        price: 2300,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 25,
        xp: 3000,
        time: 180,
      },
      {
        name: "Medium Goat",
        price: 2200,
        minQuantity: 4,
        maxQuantity: 6,
        necessaryLevel: 50,
        xp: 5600,
        time: 180,
      },
      {
        name: "Medium Cow",
        price: 2300,
        minQuantity: 8,
        maxQuantity: 11,
        necessaryLevel: 65,
        xp: 6700,
        time: 180,
      },
    ],
  },

  {
    name: "Hide",
    category: "Husbandry",
    isGathering: false,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Pig",
        price: 700,
        minQuantity: 2,
        maxQuantity: 4,
        necessaryLevel: 1,
        xp: 8000,
        time: 480,
      },
      {
        name: "Small Cow",
        price: 2300,
        minQuantity: 6,
        maxQuantity: 9,
        necessaryLevel: 25,
        xp: 20000,
        time: 1200,
      },
      {
        name: "Medium Pig",
        price: 700,
        minQuantity: 6,
        maxQuantity: 9,
        necessaryLevel: 40,
        xp: 18000,
        time: 720,
      },
      {
        name: "Medium Cow",
        price: 2300,
        minQuantity: 12,
        maxQuantity: 18,
        necessaryLevel: 65,
        xp: 27000,
        time: 1200,
      },
    ],
  },
  {
    name: "Chicken",
    category: "Husbandry",
    isGathering: false,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Small Hare Pen",
        price: 2000,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 1,
        xp: 5000,
        time: 300,
      },
      {
        name: "Small Chicken Pen",
        price: 2000,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 5,
        xp: 5000,
        time: 300,
      },
      {
        name: "Medium Chicken Pen",
        price: 2000,
        minQuantity: 7,
        maxQuantity: 12,
        necessaryLevel: 30,
        xp: 11200,
        time: 300,
      },
      {
        name: "Medium Hare Pen",
        price: 2000,
        minQuantity: 7,
        maxQuantity: 12,
        necessaryLevel: 35,
        xp: 11200,
        time: 300,
      },
      {
        name: "Medium Turkey Pen",
        price: 700,
        minQuantity: 9,
        maxQuantity: 13,
        necessaryLevel: 55,
        xp: 21400,
        time: 570,
      },
    ],
  },
  {
    name: "Wool",
    category: "Husbandry",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Small Goat",
        price: 2200,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 10,
        xp: 2500,
        time: 150,
      },
      {
        name: "Small Sheep",
        price: 2900,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 20,
        xp: 5000,

        time: 300,
      },
      {
        name: "Medium Goat",
        price: 2200,
        minQuantity: 2,
        maxQuantity: 4,
        necessaryLevel: 50,
        xp: 5600,
        time: 150,
      },
      {
        name: "Medium Sheep",
        price: 2900,
        minQuantity: 8,
        maxQuantity: 11,
        necessaryLevel: 65,
        xp: 11200,
        time: 300,
      },
    ],
  },
  {
    name: "Cheese",
    category: "Husbandry",
    isGathering: false,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Cheese Barrel",
        price: 2300,
        minQuantity: 1,
        maxQuantity: 2,
        necessaryLevel: 21,
        xp: 7500,
        time: 1800,
      },
    ],
  },
  {
    name: "Beef",
    category: "Husbandry",
    isGathering: false,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Small Cow",
        price: 2300,
        minQuantity: 6,
        maxQuantity: 11,
        necessaryLevel: 25,
        xp: 20000,
        time: 1200,
      },
      {
        name: "Medium Cow",
        price: 2300,
        minQuantity: 15,
        maxQuantity: 22,
        necessaryLevel: 65,
        xp: 45000,
        time: 1200,
      },
    ],
  },

  //Woodcutting
  {
    name: "Log",
    category: "Woodcutting",
    isGathering: true,
    isCrafting: false,
    isDroplable: false,

    source: [
      {
        name: "Junipper",
        price: 630,
        minQuantity: 3,
        maxQuantity: 5,
        necessaryLevel: 1,
        xp: 2000,
        time: 120,
      },
      {
        name: "Fir",
        price: 630,
        minQuantity: 13,
        maxQuantity: 16,
        necessaryLevel: 5,
        xp: 8000,
        time: 480,
      },
      {
        name: "Palm",
        price: 630,
        minQuantity: 10,
        maxQuantity: 13,
        necessaryLevel: 10,
        xp: 6000,
        time: 360,
      },
      {
        name: "Oak",
        price: 630,
        minQuantity: 35,
        maxQuantity: 52,
        necessaryLevel: 20,
        xp: 24000,
        time: 1440,
      },
      {
        name: "Wildleaf",
        price: 630,
        minQuantity: 25,
        maxQuantity: 35,
        necessaryLevel: 35,
        xp: 16000,
        time: 960,
      },
      {
        name: "Willow",
        price: 630,
        minQuantity: 16,
        maxQuantity: 30,
        necessaryLevel: 50,
        xp: 12000,
        time: 720,
      },
    ],
  },

  //Cooking
  {
    name: "Ground Flour",
    category: "Cooking",
    isGathering: false,
    isCrafiting: true,
    materials: [
      { name: "Wheat", quantity: 10, tax: 50, experience: 830 },
      { name: "Potato", quantity: 10, tax: 18, experience: 300 },
      { name: "Corn", quantity: 10, tax: 100, experience: 1660 },
    ],
    source: [
      {
        name: "Wheat",
        price: 800,
        minQuantity: 10,
        maxQuantity: 10,
        necessaryLevel: 1,
        xp: 830,
        time: 60,
      },
      {
        name: "Potato",
        price: 518,
        minQuantity: 10,
        maxQuantity: 10,
        necessaryLevel: 1,
        xp: 300,
        time: 60,
      },
      {
        name: "Corn",
        price: 1600,
        minQuantity: 10,
        maxQuantity: 10,
        necessaryLevel: 1,
        xp: 1660,
        time: 60,
      },

    ],
  },
  //Mining
  {
    name: "Salt Bowl",
    category: "Mining",
    isGathering: false,
    isCrafting: false,
    isDroplable: true,
    source: [
      {
        name: "Droping",
        price: 0,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 1,
        xp: 0,
        time: 0,
      },
    ],
  },
  {
    name: "Coal",
    category: "Mining",
    isGathering: false,
    isCrafting: false,
    isDroplable: false,
    source: [
      {
        name: "Coal",
        price: 0,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 10,
        xp: 0,
        time: 0,
      },
    ],
  },
  {
    name: "Stone", 
    category: "Mining",
    isGathering: false,
    isCrafting: false,
    isDroplable: true,
    source: [
      {
        name: "Droping",
        price: 0,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 1,
        xp: 0,
        time: 0,
      },
    ],
  },
  //Fishing
  {
    name: "Sliced Fish",
    category: "Fishing",
    isGathering: false,
    isCrafting: false,
    isDroplable: false,
    source: [
      { 
        name: "Fishing",
        price: 0,
        minQuantity: 1,
        maxQuantity: 1,
        necessaryLevel: 1,
        xp: 0,
        time: 0,
      },
    ],
  },
  



];
